//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy3.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolModuleTable
    {
        public int SchoolIdentity { get; set; }
        public string SchoolName { get; set; }
        public int NumberOfStudents { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    }
}
